name: quizproject
on:
  push:
    branches:
      - main
      - origin
  pull_request:
    branches:
      - main
      - origin
jobs:
  first:
    name: install ubuntu
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1
          POSTGRES_DB: quizproject
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Update
        run: sudo apt update
      - name: check out repo
        uses: actions/checkout@v3
      - name: Install python3-pip
        run: sudo apt install python3-pip
      - name: Requirements install
        run: pip install -r requirements.txt
      - name: Run test
        env:
          DJANGO_SETTINGS_MODULE: core.settings.local
          SECRET_KEY: django-insecure-ht4)3u=$b4a7vgiym=j)f*5l$c0-#n0ydnl_(&b(^0kpl^7+7j
          SQL_ENGINE: django.db.backends.postgresql
          SQL_DATABASE: quizproject
          SQL_USER: postgres
          SQL_PASSWORD: 1
          SQL_HOST: localhost
          SQL_PORT: 5432
        run: python manage.py test
